services:
    _defaults:
        public: true

    hraph_sylius_paygreen_plugin.client.paygreen_api_default_config:
        class: Hraph\SyliusPaygreenPlugin\Types\ApiConfig
        arguments:
            - "%hraph_sylius_paygreen_plugin.client.username%" # Parameter fitted in with username dynamically on load
            - "%hraph_sylius_paygreen_plugin.client.api_key%" # Parameter fitted in with api_key dynamically on load

    hraph_sylius_paygreen_plugin.client.paygreen_api_default_options:
        class: Hraph\SyliusPaygreenPlugin\Types\ApiOptions
        arguments:
            - "%hraph_sylius_paygreen_plugin.client.sandbox%" # Parameter fitted in with sandbox dynamically on load
            - "%hraph_sylius_paygreen_plugin.client.payment_type%" # Parameter fitted in with payment_type dynamically on load

    hraph_sylius_paygreen_plugin.client.paygreen_api_factory:
        class: Hraph\SyliusPaygreenPlugin\Client\PaygreenApiFactory
        arguments:
            - "@hraph_sylius_paygreen_plugin.client.paygreen_api_default_config"
            - "@hraph_sylius_paygreen_plugin.client.paygreen_api_default_options"

    hraph_sylius_paygreen_plugin.client.paygreen_api_manager:
        class: Hraph\SyliusPaygreenPlugin\Client\PaygreenApiManager
        arguments:
            - "@hraph_sylius_paygreen_plugin.client.repository.paygreen_api_shop_repository"
            - "@hraph_sylius_paygreen_plugin.client.repository.paygreen_api_transfer_repository"
            - "@hraph_sylius_paygreen_plugin.repository.paygreen_shop"
            - "@hraph_sylius_paygreen_plugin.client.paygreen_api_default_config"
            - "@doctrine.orm.default_entity_manager"

    hraph_sylius_paygreen_plugin.client.repository.paygreen_api_shop_repository:
        class: Hraph\SyliusPaygreenPlugin\Client\Repository\PaygreenApiShopRepository
        arguments:
            - "@hraph_sylius_paygreen_plugin.client.paygreen_api_factory"
            - "@hraph_sylius_paygreen_plugin.provider.paygreen_shop"
            - "@monolog.logger"

    hraph_sylius_paygreen_plugin.client.repository.paygreen_api_transfer_repository:
        class: Hraph\SyliusPaygreenPlugin\Client\Repository\PaygreenApiTransferRepository
        arguments:
            - "@hraph_sylius_paygreen_plugin.client.paygreen_api_factory"
            - "@hraph_sylius_paygreen_plugin.provider.paygreen_transfer"
            - "@monolog.logger"

    hraph_sylius_paygreen_plugin.client.adapter.paygreen_transfer_api_status_adapter:
        class: Hraph\SyliusPaygreenPlugin\Client\Adapter\PaygreenTransferApiStatusAdapter

    hraph_sylius_paygreen_plugin.client.adapter.paygreen_payment_api_status_adapter:
        class: Hraph\SyliusPaygreenPlugin\Client\Adapter\PaygreenPaymentApiStatusAdapter
