services:
    _defaults:
        public: true

    hraph_sylius_paygreen_plugin.provider.paygreen_shop:
        class: Hraph\SyliusPaygreenPlugin\Provider\PaygreenShopProvider
        arguments:
            - "@hraph_sylius_paygreen_plugin.repository.paygreen_shop"
            - "@hraph_sylius_paygreen_plugin.factory.paygreen_shop"

    hraph_sylius_paygreen_plugin.provider.paygreen_transfer:
        class: Hraph\SyliusPaygreenPlugin\Provider\PaygreenTransferProvider
        arguments:
            - "@hraph_sylius_paygreen_plugin.repository.paygreen_transfer"
            - "@hraph_sylius_paygreen_plugin.factory.paygreen_transfer"

    hraph_sylius_paygreen_plugin.provider.gateway_config:
        class: Hraph\SyliusPaygreenPlugin\Provider\GatewayConfigProvider
        arguments:
            - "@sylius.repository.gateway_config"
            - "@sylius.factory.payment_method"
            - "@sylius.repository.payment_method"
