imports:
    - { resource: "services/form.yaml" }
    - { resource: "services/gateway_factory.yaml" }
    - { resource: "services/action.yaml" }
    - { resource: "services/helper.yaml" }
    - { resource: "services/controller.yaml" }
    - { resource: "services/console.yaml" }
    - { resource: "services/event_listener.yaml" }
    - { resource: "services/client.yaml" }
    - { resource: "services/menu.yaml" }
    - { resource: "services/state_machine.yaml" }
    - { resource: "services/provider.yaml" }
    - { resource: "services/extension.yaml" }

services:
    _defaults:
        public: true

    hraph_sylius_paygreen_plugin.request.get_http_request:
        class: Payum\Core\Request\GetHttpRequest
